version: "3.9"

services:
  dev:
    image: bmagyar/roscon2023_workshop
    network_mode: host
    init: true
    environment:
      # Wall off ROS, when this is FALSE, ROS_DOMAIN_ID is important to set
      - ROS_LOCALHOST_ONLY=1
      # Settings to make graphical programs work
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      # Workspace mount
      - ./ws:/home/ros/ws
      # Settings to make graphical programs work
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev/dri:/dev/dri
    # this adds docker -it
    stdin_open: true # docker run -i
    tty: true        # docker run -t
