hercules_1_publisher_port_joint_trajectory_controller:
  ros__parameters:

    controller_name: "hercules_1/port_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [-1.57, 3.14, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [-1.57, 3.925, 0.0, -1.57, 0.0, -0.785]
    pos3:
      positions: [-1.57, 3.14, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [-1.57, 3.14, 0.0, -1.57, 0.0, 0.0]

    joints:
      - hercules_1/port_shoulder_pan_joint
      - hercules_1/port_shoulder_lift_joint
      - hercules_1/port_elbow_joint
      - hercules_1/port_wrist_1_joint
      - hercules_1/port_wrist_2_joint
      - hercules_1/port_wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      hercules_1/port_shoulder_pan_joint: [-0.1,0.1]
      hercules_1/port_shoulder_lift_joint: [-1.6,-1.5]
      hercules_1/port_elbow_joint: [-0.1,0.1]
      hercules_1/port_wrist_1_joint: [-1.6,-1.5]
      hercules_1/port_wrist_2_joint: [-0.1,0.1]
      hercules_1/port_wrist_3_joint: [-0.1,0.1]


hercules_1_publisher_starboard_joint_trajectory_controller:
  ros__parameters:

    controller_name: "hercules_1/starboard_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [1.57, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [1.57, -0.785, 0.0, -0.785, 0.0, 0.785]
    pos3:
      positions: [1.57, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [1.57, 0.0, 0.0, -1.57, 0.0, 0.0]

    joints:
      - hercules_1/starboard_shoulder_pan_joint
      - hercules_1/starboard_shoulder_lift_joint
      - hercules_1/starboard_elbow_joint
      - hercules_1/starboard_wrist_1_joint
      - hercules_1/starboard_wrist_2_joint
      - hercules_1/starboard_wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      hercules_1/starboard_shoulder_pan_joint: [-0.1,0.1]
      hercules_1/starboard_shoulder_lift_joint: [-1.6,-1.5]
      hercules_1/starboard_elbow_joint: [-0.1,0.1]
      hercules_1/starboard_wrist_1_joint: [-1.6,-1.5]
      hercules_1/starboard_wrist_2_joint: [-0.1,0.1]
      hercules_1/starboard_wrist_3_joint: [-0.1,0.1]


hercules_1_publisher_port_gripper_controller:
  ros__parameters:

    publish_topic: "hercules_1/port_gripper_controller/commands"
    wait_sec_between_publish: 1
    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.0]
    pos2: [0.23]
    pos3: [0.8]
    pos4: [0.53]


hercules_1_publisher_starboard_gripper_controller:
  ros__parameters:

    publish_topic: "hercules_1/starboard_gripper_controller/commands"
    wait_sec_between_publish: 1
    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.8]
    pos4: [0.53]
    pos3: [0.0]
    pos2: [0.23]



hercules_2_publisher_port_joint_trajectory_controller:
  ros__parameters:

    controller_name: "hercules_2/port_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [-1.57, 3.14, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [-1.57, 3.925, 0.0, -1.57, 0.0, -0.785]
    pos3:
      positions: [-1.57, 3.14, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [-1.57, 3.14, 0.0, -1.57, 0.0, 0.0]

    joints:
      - hercules_2/port_shoulder_pan_joint
      - hercules_2/port_shoulder_lift_joint
      - hercules_2/port_elbow_joint
      - hercules_2/port_wrist_1_joint
      - hercules_2/port_wrist_2_joint
      - hercules_2/port_wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      hercules_2/port_shoulder_pan_joint: [-0.1,0.1]
      hercules_2/port_shoulder_lift_joint: [-1.6,-1.5]
      hercules_2/port_elbow_joint: [-0.1,0.1]
      hercules_2/port_wrist_1_joint: [-1.6,-1.5]
      hercules_2/port_wrist_2_joint: [-0.1,0.1]
      hercules_2/port_wrist_3_joint: [-0.1,0.1]


hercules_2_publisher_starboard_joint_trajectory_controller:
  ros__parameters:

    controller_name: "hercules_2/starboard_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [1.57, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2:
      positions: [1.57, -0.785, 0.0, -0.785, 0.0, 0.785]
    pos3:
      positions: [1.57, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4:
      positions: [1.57, 0.0, 0.0, -1.57, 0.0, 0.0]

    joints:
      - hercules_2/starboard_shoulder_pan_joint
      - hercules_2/starboard_shoulder_lift_joint
      - hercules_2/starboard_elbow_joint
      - hercules_2/starboard_wrist_1_joint
      - hercules_2/starboard_wrist_2_joint
      - hercules_2/starboard_wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      hercules_2/starboard_shoulder_pan_joint: [-0.1,0.1]
      hercules_2/starboard_shoulder_lift_joint: [-1.6,-1.5]
      hercules_2/starboard_elbow_joint: [-0.1,0.1]
      hercules_2/starboard_wrist_1_joint: [-1.6,-1.5]
      hercules_2/starboard_wrist_2_joint: [-0.1,0.1]
      hercules_2/starboard_wrist_3_joint: [-0.1,0.1]


hercules_2_publisher_port_gripper_controller:
  ros__parameters:

    publish_topic: "hercules_2/port_gripper_controller/commands"
    wait_sec_between_publish: 1
    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.0]
    pos2: [0.23]
    pos3: [0.8]
    pos4: [0.53]


hercules_2_publisher_starboard_gripper_controller:
  ros__parameters:

    publish_topic: "hercules_2/starboard_gripper_controller/commands"
    wait_sec_between_publish: 1
    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.8]
    pos4: [0.53]
    pos3: [0.0]
    pos2: [0.23]
